const { CASH_FLOW_OBJECT } = require('@utils/const');

const LINES = [
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.COMMISSION_OTA,
		line: 74,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.TRANSACTION_FEE,
		line: 75,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.REFUND,
		line: 76,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		line: 78,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.HOST_BANK_ACCOUNT,
		line: 79,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.CASH_FUND,
		line: 80,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.HOST_CASH_FUND,
		line: 81,
	},
	{
		from: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		to: CASH_FLOW_OBJECT.COMMISSION_tb,
		line: 84,
	},
];

module.exports = {
	name: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
	LINES,
};
