const { CASH_FLOW_OBJECT } = require('@utils/const');

const LINES = [
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.BACKUP_CASH_FUND,
		line: 33,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.COMMISSION_OTA,
		line: 34,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.SERVICES,
		line: 35,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.TAX,
		line: 36,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.HOST_INCOME,
		line: 37,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.MANAGE_FEE,
		line: 38,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.MAINTENANCE,
		line: 39,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.BUY_EQUIPMENT,
		line: 40,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.OTHER_FEE,
		line: 41,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.TRANSACTION_FEE,
		line: 42,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.REFUND,
		line: 43,
	},
	{
		from: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
		to: CASH_FLOW_OBJECT.COMMISSION_tb,
		line: 85,
	},
];

module.exports = {
	name: CASH_FLOW_OBJECT.COMPANY_BANK_ACCOUNT,
	LINES,
};
