const udf = undefined;
export const resetParams = {
  common: {
    limit: undefined,
    start: undefined,
    room: undefined,
    home: undefined,
  },
  income_list: {
    showSMS: undefined,
    ota: undefined,
    createdBy: undefined,
    collector: undefined,
    paymentState: undefined,
    payoutType: undefined,
    hosting: undefined,
    source: undefined,
    serviceType: undefined,
    status: undefined,
    isOwnerCollect: undefined,
    isAvoidTransactionFee: undefined,
    isEmptyBookingId: undefined,
    isCalcDeposit: undefined,
    otaBookingId: undefined,
    description: undefined,
    sms: undefined,

    dateType: undefined,
  },
  income_profession: {
    confirmedBy: udf,
    confirmed: udf,
    confirmPaid: udf,
    range: udf,
    name: udf,
    createdBy: udf,
    dateKey: udf,
    sms: udf,
    from: udf,
    to: udf,
  },
  prepayment_list: {},
  debt: {},
};
