extends:
  - airbnb-base
  - eslint-config-prettier

plugins:
  - eslint-plugin-prettier

parserOptions:
  ecmaVersion: 2018

rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  no-tabs: 0
  global-require: 0
  camelcase: 0
  no-multi-assign: 0
  func-names: 0
  consistent-return: 0
  radix: 0
  no-param-reassign: 0
  no-return-await: 0
  no-extend-native: 0
  no-restricted-syntax: 0
  no-plusplus: 0
  no-unused-vars: 1
  max-len: 0
  no-underscore-dangle: 0
  no-new: 0
  no-continue: 0
  prefer-const: 0
  no-await-in-loop: 0
  no-use-before-define: 0
  no-console: 0
  no-func-style: 0
  no-constant-condition: 0
  import/no-unresolved: 0
  guard-for-in: 0
  prefer-promise-reject-errors: 0
  no-nested-ternary: 0
  import/no-dynamic-require: 0
  prefer-destructuring: 0
