const ACTIONS = {
	FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
	MAKE_TRANSFER_REQUEST: 'MAKE_TRANSFER_REQUEST',
	CANCEL_TRANSFER_REQUEST: 'CANCEL_TRANSFER_REQUEST',
	MAKE_BULK_TRANSFER_REQUEST: 'MAKE_BULK_TRANSFER_REQUEST',
};

module.exports = {
	ACTIONS,
};
