import type { Metadata } from "next";
import LayoutComponent from "../components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Endless Passion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: "0px" }}>
        <LayoutComponent>{children}</LayoutComponent>
      </body>
    </html>
  );
}
