const EXIT = 'EXIT';
const FINANCE_EARNING_STATS = 'FINANCE_EARNING_STATS';
const REPORT_CALCULATOR = 'REPORT_CALCULATOR';
const FILE_COMPRESS_IMAGE = 'FILE_COMPRESS_IMAGE';
const FILE_CRAWLER = 'FILE_CRAWLER';
const PAYMENT_CRAWLER = 'PAYMENT_CRAWLER';
const REVIEW_CRAWLER = 'REVIEW_CRAWLER';
const SYNC_CALENDAR = 'SYNC_CALENDAR';
const SYNC_PRICE = 'SYNC_PRICE';
const SYNC_CALENDAR_LOCAL = 'SYNC_CALENDAR_LOCAL';
// Puppeteer
const GENERATE_IMAGE_PATH = 'GENERATE_IMAGE_PATH';
const GENERATE_PDF_PATH = 'GENERATE_PDF_PATH';
const GENERATE_EXCEL_TO_IMG = 'GENERATE_EXCEL_TO_IMG';

module.exports = {
	REPORT_CALCULATOR,
	FINANCE_EARNING_STATS,
	PAYMENT_CRAWLER,
	REVIEW_CRAWLER,
	SYNC_CALENDAR,
	SYNC_PRICE,
	SYNC_CALENDAR_LOCAL,
	FILE_COMPRESS_IMAGE,
	FILE_CRAWLER,
	GENERATE_IMAGE_PATH,
	EXIT,
	GENERATE_EXCEL_TO_IMG,
	GENERATE_PDF_PATH,
};
