import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavLinks } from "../components/nav-links";
// import LayoutComponent from "../components/Layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Home",
    template: "%s | Bao",
  },
  description: "Generated by create next app",
  icons: {
    icon: "images/koi_1.png",
    shortcut: "images/koi_1.png",
    apple: "images/koi_1.png",
  },
};

export default function RootLayout({
  children,
  // auth,
  modal,
}: Readonly<{
  children: React.ReactNode;
  // auth: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {modal}
        <div id="modal-root" />
      </body>
    </html>
  );
}
