const ZALO_TYPE = {
	MSG_SEEN: 3,
	MSG_DELIVERED: 2,
	MSG_LOCAL: 10,
	MSG_SENT: 1,
	MSG_CHECKING_EXIST: -20,
	MSG_FORWARDING: -21,
	MSG_FILE_EXPIRED: -22,
	MSG_UPLOAD_LOCAL: -23,
	MSG_FAIL: -2,
	MSG_CANCEL: -7,
	MSG_READ: 4,
	MSG_INFO: -4,
	MSG_GROUP_NOTI: -6,
	MSG_ERROR_INFO: -5,
	MSG_AFTER_READ: 5,
	MSG_ARTICLE: 0,
	MSG_TEXT: 1,
	MSG_STICKER: 4,
	MSG_STICKER_2: 13,
	MSG_FILE: 19,
	MSG_PHOTO: 2,
	MSG_PHOTO_2: 11,
	MSG_VOICE: 3,
	MSG_DOODLE: 5,
	MSG_GIF: 7,
	MSG_CONTACT: 6,
	MSG_VIDEO: 18,
	MSG_LOCATION: 17,
	MSG_UNDO: 20,
	MSG_OA: 21,
	MSG_ECARD: 25,
	MSG_POLL: 26,
	MSG_DEL_EVERYONE: -27,
	MSG_UNKNOWN: -3,
	MSG_PHOTO_GROUP: 2503,
	MSG_FRIEND_SENT_REQUEST: 2504,
	MSG_SUGGEST_IN_CHAT: 2505,
	MSG_TODO: 2506,
	MSG_PHOTO_THUMB_DONE: 101,
	MSG_FOLDER: 23,
	MSG_LINK_CLIENT: 1805,
	MSG_SUBTYPE_PHOTO: 1,
	MSG_SUBTYPE_GIF: 2,
	MSG_SUBTYPE_LINK: 3,
	MSG_FOLDER_STATE: {
		ZIPPING: 120,
		UNZIPPING: 121,
		DONE_ZIP: 123,
	},
	MSG_SRC: {
		POLL: 1,
		SYNC_MOBILE_MESSAGE: 2,
		CLOUD: 3,
	},
	CLI_MSG_TYPE_TEXT: 1,
	CLI_MSG_TYPE_VOICE: 31,
	CLI_MSG_TYPE_PHOTO: 32,
	CLI_MSG_TYPE_STICKER: 36,
	CLI_MSG_TYPE_DOODLE: 37,
	CLI_MSG_TYPE_CONTACT: 38,
	CLI_MSG_TYPE_LINK: 40,
	CLI_MSG_TYPE_VIDEO: 44,
	CLI_MSG_TYPE_FILE: 46,
	CLI_MSG_TYPE_GIF: 49,
	CLI_MSG_TYPE_LOCATION: 43,
};

const ZALO_CONFIG = {
	stickerUrl: 'https://zalo-api.zadn.vn/api/emoticon/sprite?size=130&eid=',
};

const OTT_NAME = 'zalo';

const CONNECTION_TYPE = {
	EXTENSION: 'extension',
	SERVER_SERVICE: 'server_service',
};

const ZALO_SENT = 'ZALO_SENT';
const SEND_TEXT = 'SEND_TEXT';
const SEND_IMAGE = 'SEND_IMAGE';
const USER_LOGIN = 'USER_LOGIN';
// const GET_MESSAGES = 'GET_MESSAGES';
const LOGIN = 'LOGIN';
const ADD_FRIEND = 'ADD_FRIEND';
const CHECK_EXISTS = 'CHECK_EXISTS';
const CHECK_LOGIN = 'CHECK_LOGIN';
const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';
// const GET_USERS = 'GET_USERS';
const FORWARD_MSGS = 'FORWARD_MSGS';
const ON_NEW_MESSAGE = 'ON_NEW_MESSAGE';
const CHECK_CONNECTION = 'CHECK_CONNECTION';

module.exports = {
	ZALO_TYPE,
	ZALO_CONFIG,
	OTT_NAME,
	CONNECTION_TYPE,
	ZALO_SENT,
	SEND_TEXT,
	SEND_IMAGE,
	USER_LOGIN,
	LOGIN,
	ADD_FRIEND,
	CHECK_EXISTS,
	CHECK_LOGIN,
	USER_LOGIN_STATUS,
	FORWARD_MSGS,
	ON_NEW_MESSAGE,
	CHECK_CONNECTION,
};
