const TYPES = {
	WEBEXT_GET_HEADER: 'WEBEXT_GET_HEADER',
	WEBEXT_GET_HEADER_POSTBACK: 'WEBEXT_GET_HEADER_RESPONSE_POSTBACK',

	WEBEXT_SEND_REQUEST: 'WEBEXT_SEND_REQUEST',
	WEBEXT_SEND_REQUEST_POSTBACK: 'WEBEXT_SEND_REQUEST_POSTBACK',

	WEBEXT_SEND_CUSTOM_REQUEST: 'WEBEXT_SEND_CUSTOM_REQUEST',
	WEBEXT_SEND_CUSTOM_REQUEST_POSTBACK: 'WEBEXT_SEND_CUSTOM_REQUEST_POSTBACK',
};

module.exports = {
	TYPES,
};
