const minusSmall = 30;

export const smallSize = {
  PADDING_FIRST_EACH_NODE_OF_GROUP: 80,
  HEIGHT_NODE_GUEST: 440 - minusSmall / 2,
  WIDTH_NODE_GUEST: 150 - minusSmall / 2,
  HEIGTH_FOOTER_NODE_GROUP: 100,
  HEIGHT_NODE: 75 - minusSmall / 3,
  WIDTH_NODE: 170 - minusSmall,
  LIMIT_AMOUNT_NODE_FOR_TOP: 7,
  HEIGHT_GROUP: 900,
  WIDTH_GROUP_FIRST: 200,
  SOURCE_X_EDGE: 45,
  SOURCE_Y_EDGE: 20,
  TEXT_NODE: 14,
  NUMBER_NODE: 14,
  POSITION_NODE_Y: 100,
  POSITION_NODE_FIRST_Y: 85,
  TEXT_TRANSFORM: 30,

  TEXT_FIRST_FOOTER_GROUP: 18,
  TEXT_SECOND_FOOTER_GROUP: 18
};

export const normalSize = {
  PADDING_FIRST_EACH_NODE_OF_GROUP: 80,
  HEIGHT_NODE_GUEST: 440,
  WIDTH_NODE_GUEST: 150,
  HEIGTH_FOOTER_NODE_GROUP: 100,
  HEIGHT_NODE: 75,
  WIDTH_NODE: 170,
  LIMIT_AMOUNT_NODE_FOR_TOP: 7,
  HEIGHT_GROUP: 900,
  WIDTH_GROUP_FIRST: 250,
  SOURCE_X_EDGE: 55,
  SOURCE_Y_EDGE: 24,
  TEXT_NODE: 16,
  NUMBER_NODE: 16,
  POSITION_NODE_Y: 115,
  POSITION_NODE_FIRST_Y: 85,
  TEXT_TRANSFORM: 40,

  TEXT_FIRST_FOOTER_GROUP: 20,
  TEXT_SECOND_FOOTER_GROUP: 20
};
